EBandPlannerROS:

  # TRAJECTORY CONTROL
  differential_drive: true

  # velocity limits
  max_vel_lin: 1.0
  max_vel_th: 0.75
  min_vel_lin: 0.25
  min_in_place_vel_th: 0.3

  # goal tolerance
  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 3.15

  # angular velocity PID
  k_prop: 1.0

  #eband parameters
